// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyyX4zgSIBT2ojnZ1wtCclp4crI-nze7E',
    appId: '1:309485968777:web:49372b6545a34a7e45d558',
    messagingSenderId: '309485968777',
    projectId: 'messaging-app-one',
    authDomain: 'messaging-app-one.firebaseapp.com',
    storageBucket: 'messaging-app-one.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUWhfUTqRRYXUfXbvpd7FaSe4eGhfkvP0',
    appId: '1:309485968777:android:cc8b3a28530047db45d558',
    messagingSenderId: '309485968777',
    projectId: 'messaging-app-one',
    storageBucket: 'messaging-app-one.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy_oItVjFeuSGZ55EjiggUErQEqZjvVIs',
    appId: '1:309485968777:ios:8b893cb369fb2a1c45d558',
    messagingSenderId: '309485968777',
    projectId: 'messaging-app-one',
    storageBucket: 'messaging-app-one.appspot.com',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy_oItVjFeuSGZ55EjiggUErQEqZjvVIs',
    appId: '1:309485968777:ios:bc585246379794d945d558',
    messagingSenderId: '309485968777',
    projectId: 'messaging-app-one',
    storageBucket: 'messaging-app-one.appspot.com',
    iosBundleId: 'com.example.messagingApp.RunnerTests',
  );
}
